apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: ai-ns
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30089
  type: NodePort
